baseURL      = "https://andornot.xyz"
languageCode = "en-us"
title        = "The Third Gate"
theme        = "hugo-theme-stack"

defaultContentLanguage = "zh-cn"
hasCJKLanguage         = true

[pagination]
    pagerSize = 5

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = "andornot-xyz"

[services.googleAnalytics]
    id = "G-XCEK8PL0RD"
