language: go

dist: trusty

sudo: false

env:
  - HUGO_VERSION=0.74.3

install: true

before_script:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
  - sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
  - rm -rf public || exit 0

script:
  - hugo -v --gc --minify
  - echo 'andornot.xyz' > public/CNAME

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master

branches:
  only:
  - next
