jobs:
  include:
    - language: node_js
      node_js:
        - 14
 
      before_script:
        - npm install --dev @babel/cli @babel/core @babel/preset-env browserslist clipboard cssnano postcss-cli postcss-import postcss-mixins postcss-nested postcss-preset-env postcss-url

    - language: go
      install: true
      before_script:
        - wget https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_0.74.3_Linux-64bit.deb
        - sudo dpkg -i hugo_0.74.3_Linux-64bit.deb
        - rm -rf public || exit 0
      
      script:
        - hugo -v --gc --minify
        - echo 'andornot.xyz' > public/CNAME
      
      after_script:
        - cd ./public
        - git init
        - git config user.name "igaozp"   #修改成自己的github用户名
        - git config user.email "igaozp@hotmail.com"   #修改成自己的GitHub邮箱
        - git add .
        - git commit -m "Build by Travis-CI"
        - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master #GH_token就是在travis中设置的token

      branches:
        only:
          - next

      env:
          global:
              - GH_REF: github.com/igaozp/igaozp.github.io.git

